#ifndef MY_STM32F4XX_HAL_RCC_EX_H
#define MY_STM32F4XX_HAL_RCC_EX_H

void MY_HAL_RCC_GPIOD_CLK_ENABLE(void);
void MY_HAL_RCC_GPIOA_CLK_ENABLE(void);

#define __HAL_RCC_GPIOD_CLK_ENABLE() MY_HAL_RCC_GPIOD_CLK_ENABLE()
#define __HAL_RCC_GPIOA_CLK_ENABLE() MY_HAL_RCC_GPIOA_CLK_ENABLE()

#endif